#import "../theorems.typ": *
#import "../template.typ": *


// Take a look at the file `template.typ` in the file panel
// to customize this template and discover how it works.
#show: project.with(
  title: "Test",
  authors: (
    vova,
  ),
  // Insert your abstract after the colon, wrapped in brackets.
  // Example: `abstract: [This is my abstract...]`
  abstract: [hmm…] + lorem(59),
  date: "April 30, 2023",
  font: "Kurale",
)


// We generated the example code below so you can see how
// your document will look. Go ahead and replace it with
// your own content!

= Introduction
#lorem(60)

== In this paper
#lorem(20)

=== Contributions
#lorem(40)

== Related Work
#lorem(500)

AutoGenerated Threebonacci number table (using code):

= Threebonacci numbers

#let n = 15
#let nums = range(1, n + 1)
#let threebonacci(i) = (
  if i <= 2 {
    1
  } else {
    threebonacci(i - 1) + threebonacci(i - 2) + threebonacci(i - 3)
  }
)

#table(
  columns: n,
  ..nums.map(i => $T_#i$),
  ..nums.map(i => str(threebonacci(i)))
)

== Goedel's incompleteness theorems

== First incompleteness theorem






// Start document here

= Introduction


#lemma(name: "Pythagoras")[In a right angled triangle, $ a^2 + b^2 = c^2. $]
#theorem(name: "WLLN")[#lorem(20)]
#proof[
  #lorem(30)
  $ a + i b $
  #lorem(5)
]

// Migrate this LaTeX code to typst:

// \begin{equation}
//     \int_{\Omega} g(X(w)) P(\d w) = \int_{\sR^n} g(x) P_X(\d x) = \begin{cases}
//         \sum_i g(x_i) p_X(x_i) & \text{дискретный случай} \\
//         \int_{\sR^n} g(x) p_X(x) \d x & \text{абсолютно непрерывный случай}
//     \end{cases}
// \end{equation}

// Особый случай для $n = 1$: интеграл Лебега-Стилтьеса.


// Теорема Фубини/Тонелли: проецируем на часть осей, деля интеграл на два вложенных.



// \section{Числовые характеристики случайных величин}

// \begin{definition}
//     Пусть $X$ — случайная величина. Тогда её математическим ожиданием называется число
//     \begin{equation}
//         \E X = \int_{\sR} x \d P_X(x)
//     \end{equation}
// \end{definition}


$ integral_Omega g(X(w)) P(d w) = integral_(R^n) g(x) P_X(d x) = cases(
    sum_i g(x_i) p_X(x_i) quad & #text[дискретный случай],
    integral_(R^n) g(x) p_X(x) d x quad & #text[абсолютно непрерывный случай]
) $



$
"here" & "there" \
"long" & "something else"
$

$
y &= (a+b)^2 \
&= (a+b)(a+b) \
&= a + a + a + b \
&= a^2 + 2a b + b^2 
$

Rewrite this to typst:

// \begin{theorem}[Критерий независимости с.в. для дискретного случая]
//     Случайные величины $X_1, \ldots, X_n$ независимы тогда и только тогда, когда $\forall x_1, \ldots, x_n \in \sR$:
//     \begin{equation}
//         p_{X_1, \ldots, X_n}(x_1, \ldots, x_n) = \prod_{i=1}^{n} p_{X_i}(x_i)
//     \end{equation}
// \end{theorem}

// \begin{proof}
    
//     \rightimp Очевидно из определения

//     \leftimp Пусть $B_1, \ldots, B_n \in \mathcal{B}(\sR)$. Тогда:
    
//     \begin{multline}
//         P(X_1 \in B_1, \ldots, X_n \in B_n) = \\
//         \sum_{(x_1, \ldots, x_n) \in B_1 \times \ldots \times B_n} p_{X_1, \ldots, X_n}(x_1, \ldots, x_n) = \\
//         \sum_{(x_1, \ldots, x_n) \in B_1 \times \ldots \times B_n} \prod_{i=1}^{n} p_{X_i}(x_i) = \\
//         \sum_{x_1 \in B_1} \ldots \sum_{x_n \in B_n} \prod_{i=1}^{n} p_{X_i}(x_i) = \\
//         \prod_{i=1}^{n} \sum_{x_i \in B_i} p_{X_i}(x_i) = \\
//         \prod_{i=1}^{n} P(X_i \in B_i)
//     \end{multline}
// \end{proof}

#theorem(name: "Критерий независимости с.в. для дискретного случая")[
    Случайные величины $X_1, …, X_n$ независимы тогда и только тогда, когда $forall x_1, …, x_n in RR$:

    $ p_(X_1, …, X_n)(x_1, …, x_n) = product_(i=1)^n p_(X_i)(x_i) $
]

#proof[
    $→$ Очевидно из определения

    $←$ Пусть $B_1, …, B_n in BB(RR)$. Тогда:

    $ P(X_1 in B_1, …, X_n in B_n) = \
        sum_(x_1, …, x_n in B_1 × … × B_n) p_(X_1, …, X_n)(x_1, …, x_n) = \
        sum_(x_1, …, x_n in B_1 × … × B_n) product_(i=1)^n p_(X_i)(x_i) = \
        sum_(x_1 in B_1) … sum_(x_n in B_n) product_(i=1)^n p_(X_i)(x_i) = \
        product_(i=1)^n sum_(x_i in B_i) p_(X_i)(x_i) = \
        product_(i=1)^n P(X_i in B_i) $

    $cal(F) op("dick") x → oo - ∞ sans(d) serif(d) <=   1 $
]


$ tan x = (sin x)/(cos x) $
$ op("custom",
     limits: #true)_(n->oo) n $

Rewrite to typst:

// \subsection{Некоторые распределения в связи с независимостью}

// Пусть $X_1, \ldots, X_n$ независимы и $X_i \sim \operatorname{Bern}(p)$.
// Тогда $X_1 + \ldots + X_n \sim \operatorname{Bin}(n, p)$.


// Для Пуассона: параметры складываются.

// Нормальное: сумма нормальных независимых нормальных нормальна.
// Медианы и средние кваадратичные отклонения складываются.

// Сумма $r$ независимых геометрических $\sim \operatorname{NB}\left( r, p \right)$


// \section{Об интегрировании}

// Мера образа множества при отображении.   

// \begin{equation}
//     P_X(B) = P(X \in B) = P(\{\omega \colon X(\omega) \in B\}) = P(X^{-1}(B))
// \end{equation}

// Мера, заданная таким образом, называется:

// \href{https://ru.wikipedia.org/wiki/%D0%9E%D0%B1%D1%80%D0%B0%D0%B7_%D0%BC%D0%B5%D1%80%D1%8B_%D0%BF%D0%BE%D0%B4_%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B5%D0%BC_%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F}{PushForward measure}.



== Об интегрировании

Пусть ```latex
    P_X(B) = P(X in B) = P({omega in Omega | X(omega) in B}) = P(X^(-1)(B))
```

```rust
    fn main() {
        println!("Hello, world!");
    }
```

Мера, заданная таким образом, называется:

#link("https://ru.wikipedia.org/wiki/%D0%9E%D0%B1%D1%80%D0%B0%D0%B7_%D0%BC%D0%B5%D1%80%D1%8B_%D0%BF%D0%BE%D0%B4_%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B5%D0%BC_%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F", 
    "PushForward measure")

Для непрерывных случайных величин:

_dfsgsg_

// \DeclareMathOperator{\sgn}{sgn}
// \DeclareMathOperator{\id}{id}
// \DeclareMathOperator{\rg}{rg}
// \DeclareMathOperator{\determinant}{det}

// \DeclareMathOperator{\Aut}{Aut}

// \DeclareMathOperator{\Sim}{Sim}
// \DeclareMathOperator{\Alt}{Alt}



== Prime numbers

#definition[
  A natural number is called a _prime number_ if it is greater than 1
  and cannot be written as the product of two smaller natural numbers.
]
#example[
  The numbers $2$, $3$, and $17$ are prime.
  #thmref(<cor_largest_prime>)[Corollary] shows that this list is not
  exhaustive!
]

#theorem(name: "Euclid")[
  There are infinitely many primes.
]
#proof[
  Suppose to the contrary that $p_1, p_2, dots, p_n$ is a finite enumeration
  of all primes. Set $P = p_1 p_2 dots p_n$. Since $P + 1$ is not in our list,
  it cannot be prime. Thus, some prime factor $p_j$ divides $P + 1$.  Since
  $p_j$ also divides $P$, it must divide the difference $(P + 1) - P = 1$, a
  contradiction.
]

#corollary[
  There is no largest prime number. <cor_largest_prime>
]
#corollary[
  There are infinitely many composite numbers.
]

$tilde(#text[leatherman])$

`print(1)`

https://typst.app/

== Reference me <intro>

@intro

/ Term: description
/ Term: description
/ Term: de\ scription

"sdfgdfgh sdfgd"

Tweet at us \#ad

#let x = $pi$

$#x$, $pi$



$#circle($=>$) arrow.l.double$

$.^┌s^┐$ 

// $ attach(
//   Pi, 1) $


$d$
