name: Build Typst document
on: push

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Typst
      #   uses: donRumata03/typst-action@patch-1
      #   with:
      #     source_file: CockumberTheory/practice.typ
      - name: Setup typst
        uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: 'v0.8.0'

      - name: Build typst
        run: |
          for file in ./*.typ
          do
            echo "$file"
          done
          
        # typst compile --root ./ CockumberTheory/practice.typ
        # if: success() || failure()
      - name: Add-and-commit
        uses: EndBug/add-and-commit@v9
        with:
          message: Build typst → PDF

