name: Build Typst document
on: push

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Typst
      #   uses: donRumata03/typst-action@patch-1
      #   with:
      #     source_file: CockumberTheory/practice.typ
      - name: Setup typst
        uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: 'v0.8.0'
      - name: "Setup python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install git-repo for python
        run: python -m pip install GitPython

      - name: Build typst
        run: |
          (find . -iname \*.typ | xargs -L 1 -d '\n' typst compile --root ./) || true
          
        # typst compile --root ./ CockumberTheory/practice.typ
        # if: success() || failure()
      
      - name: Generate commit message
        run: |
            echo "commitMessage=$(python ./generate_compiled_commit_message.py)" >> $GITHUB_ENV

      - name: Add-and-commit
        uses: EndBug/add-and-commit@v9
        # run: python -m pip install GitPython && python commit.py
        # if: success() || failure()
        with:
          message: ${{ env.commitMessage }}
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com


